Chore: added deploy step

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -32,11 +32,6 @@ jobs:
       - name: Set IMAGE_TAG
         run: echo "IMAGE_TAG=rameshxt/wisecow:v2.0.${{ github.run_number }}" >> $GITHUB_ENV
 
-      - name: Update K8s Deployment File
-        run: |
-          chmod +x ./image-updater.sh
-          ./image-updater.sh "$IMAGE_TAG"
-
       - name: SSH into EC2 and deploy
         uses: appleboy/ssh-action@v0.1.5
         with:
@@ -73,3 +68,8 @@ jobs:
             cd /home/ec2-user/WISECOW-DEPLOYMENT
             chmod +x image-updater.sh
             bash image-updater.sh "$IMAGE_TAG"
+
+            #3 DEPLOYMENT
+            echo "Deploying application on Kubernetes..."
+            kubectl apply -f /home/ec2-user/WISECOW-DEPLOYMENT/k8s/deployment.yaml || { echo "Error applying deployment"; exit 1; }
+            kubectl apply -f /home/ec2-user/WISECOW-DEPLOYMENT/k8s/service.yaml || { echo "Error applying service"; exit 1; }
